
package faculty.soap.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManagerEndpointImplService", targetNamespace = "http://endpoint.soap.faculty/", wsdlLocation = "http://localhost:9999/soap/faculty?wsdl")
public class ManagerEndpointImplService
    extends Service
{

    private final static URL MANAGERENDPOINTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGERENDPOINTIMPLSERVICE_EXCEPTION;
    private final static QName MANAGERENDPOINTIMPLSERVICE_QNAME = new QName("http://endpoint.soap.faculty/", "ManagerEndpointImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/soap/faculty?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGERENDPOINTIMPLSERVICE_WSDL_LOCATION = url;
        MANAGERENDPOINTIMPLSERVICE_EXCEPTION = e;
    }

    public ManagerEndpointImplService() {
        super(__getWsdlLocation(), MANAGERENDPOINTIMPLSERVICE_QNAME);
    }

    public ManagerEndpointImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGERENDPOINTIMPLSERVICE_QNAME, features);
    }

    public ManagerEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, MANAGERENDPOINTIMPLSERVICE_QNAME);
    }

    public ManagerEndpointImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGERENDPOINTIMPLSERVICE_QNAME, features);
    }

    public ManagerEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagerEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManagerEndpoint
     */
    @WebEndpoint(name = "ManagerEndpointImplPort")
    public ManagerEndpoint getManagerEndpointImplPort() {
        return super.getPort(new QName("http://endpoint.soap.faculty/", "ManagerEndpointImplPort"), ManagerEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagerEndpoint
     */
    @WebEndpoint(name = "ManagerEndpointImplPort")
    public ManagerEndpoint getManagerEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.soap.faculty/", "ManagerEndpointImplPort"), ManagerEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGERENDPOINTIMPLSERVICE_EXCEPTION!= null) {
            throw MANAGERENDPOINTIMPLSERVICE_EXCEPTION;
        }
        return MANAGERENDPOINTIMPLSERVICE_WSDL_LOCATION;
    }

}
