
package faculty.soap.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentEndpoint", targetNamespace = "http://endpoint.soap.faculty/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentEndpoint {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns faculty.soap.endpoint.StudentDTO
     * @throws NoStudentFoundException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap.faculty/StudentEndpoint/loginStudentRequest", output = "http://endpoint.soap.faculty/StudentEndpoint/loginStudentResponse", fault = {
        @FaultAction(className = NoStudentFoundException_Exception.class, value = "http://endpoint.soap.faculty/StudentEndpoint/loginStudent/Fault/NoStudentFoundException")
    })
    public StudentDTO loginStudent(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws NoStudentFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns faculty.soap.endpoint.StudentDTO
     * @throws RegisterException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap.faculty/StudentEndpoint/createStudentRequest", output = "http://endpoint.soap.faculty/StudentEndpoint/createStudentResponse", fault = {
        @FaultAction(className = RegisterException_Exception.class, value = "http://endpoint.soap.faculty/StudentEndpoint/createStudent/Fault/RegisterException")
    })
    public StudentDTO createStudent(
        @WebParam(name = "arg0", partName = "arg0")
        StudentDTO arg0)
        throws RegisterException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns faculty.soap.endpoint.StudentDTO
     * @throws NoStudentFoundException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap.faculty/StudentEndpoint/getStudentInfoRequest", output = "http://endpoint.soap.faculty/StudentEndpoint/getStudentInfoResponse", fault = {
        @FaultAction(className = NoStudentFoundException_Exception.class, value = "http://endpoint.soap.faculty/StudentEndpoint/getStudentInfo/Fault/NoStudentFoundException")
    })
    public StudentDTO getStudentInfo(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0)
        throws NoStudentFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns faculty.soap.endpoint.StudentDTO
     * @throws NoStudentFoundException_Exception
     */
    @WebMethod(operationName = "GetAllStudent")
    @WebResult(partName = "return")
    @Action(input = "http://endpoint.soap.faculty/StudentEndpoint/GetAllStudentRequest", output = "http://endpoint.soap.faculty/StudentEndpoint/GetAllStudentResponse", fault = {
        @FaultAction(className = NoStudentFoundException_Exception.class, value = "http://endpoint.soap.faculty/StudentEndpoint/GetAllStudent/Fault/NoStudentFoundException")
    })
    public StudentDTO getAllStudent()
        throws NoStudentFoundException_Exception
    ;

}
